before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y python-pip
  - sudo pip install --upgrade setuptools
  - sudo pip install gigalixir
script:
  - gigalixir login -e "$GIGALIXIR_EMAIL" -p "$GIGALIXIR_PASSWORD" -y
  - gigalixir domains:add $GIGALIXIR_SITE_DOMAIN -a $GIGALIXIR_APP_NAME
  - gigalixir domains:add www.$GIGALIXIR_SITE_DOMAIN -a $GIGALIXIR_APP_NAME
  - rm -r .git --force
  - git init
  - git commit -m "$GIGALIXIR_SITE_DOMAIN"
  - gigalixir git:remote $GIGALIXIR_APP_NAME
  - git push -f gigalixir HEAD:refs/heads/master
language: elixir
elixir: 1.5.1
otp_release: 20.0
dist: xenial
